// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using bicycles.Models;

namespace bicycles.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20180730221642_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571");

            modelBuilder.Entity("bicycles.Models.Bike", b =>
                {
                    b.Property<int>("BikeId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Descr");

                    b.Property<string>("Img");

                    b.Property<string>("Location");

                    b.Property<int>("Price");

                    b.Property<int?>("SellerUserId");

                    b.Property<string>("Title");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("BikeId");

                    b.HasIndex("SellerUserId");

                    b.ToTable("bikes");
                });

            modelBuilder.Entity("bicycles.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FN");

                    b.Property<string>("LN");

                    b.Property<string>("Password");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("bicycles.Models.Bike", b =>
                {
                    b.HasOne("bicycles.Models.User", "Seller")
                        .WithMany("MyBikes")
                        .HasForeignKey("SellerUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
